name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check rustfmt
      run: cargo fmt --check

  miri_stable:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: miri, rust-src
    - name: Install cargo-nextest
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Run tests x86_64-unknown-linux-gnu (little-endian)
      run: |
        cargo miri nextest run --verbose --target x86_64-unknown-linux-gnu -j4 --test stable
    - name: Run tests mips64-unknown-linux-gnuabi64 (big-endian)
      run: |
        cargo miri test --verbose --target mips64-unknown-linux-gnuabi64 --test stable random_z1

  miri_unstable:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: miri, rust-src
    - name: Install cargo-nextest
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Run tests x86_64-unknown-linux-gnu (little-endian)
      run: |
        cargo miri nextest run --verbose --target x86_64-unknown-linux-gnu -j4 --test unstable
    - name: Run tests mips64-unknown-linux-gnuabi64 (big-endian)
      run: |
        cargo miri test --verbose --target mips64-unknown-linux-gnuabi64 --test unstable random_z1

  asan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Run tests
      run: bash -c "for i in {0..10}; do RUSTFLAGS=-Zsanitizer=address cargo test --release; done"

  old_rust_rustc_1_51:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.51.0
        profile: minimal
        override: true
    - name: Build debug
      run: cargo build
    - name: Build release
      run: cargo build --release
